csv-object:
  file-name: "temp.csv"
  directory-of-java-fIle: "/Users/arditmete/DemoCsv/src/main/java/sella/democsv"
  package-name: "csvClassGenerated"
  package-route: "sella.democsv.csvClassGenerated"
  firstCsvName: "FirstCsvObject"
  secondCsvName: "SecondCsvObject"